// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHub.Data;

#nullable disable

namespace StudentHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241211234216_migracijaBrojDva")]
    partial class migracijaBrojDva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("KorisnikId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ZahtjevId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.HasIndex("ZahtjevId");

                    b.ToTable("Dokument", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NastavnoOsobljeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<int>("brojBodova")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NastavnoOsobljeId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Ispit", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Korisnik", b =>
                {
                    b.Property<long>("JMBG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JMBG"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("JMBG");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GodinaStudija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("NastavniPlan", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.NastavnoOsoblje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("JMBG")
                        .HasColumnType("bigint");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JMBG");

                    b.ToTable("NastavnoOsoblje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("NastavnoOsobljeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NastavnoOsobljeId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Obavjestenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("NastavnoOsobljeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<float>("Vrijednost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NastavnoOsobljeId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocjena", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<long>("NastavniPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("NastavnoOsobljeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NastavniPlanId");

                    b.HasIndex("NastavnoOsobljeId");

                    b.ToTable("Predmet", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<long>("IspitId")
                        .HasColumnType("bigint");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IspitId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prijava", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.Property<long>("BrojIndeksa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BrojIndeksa"));

                    b.Property<int>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<long>("JMBG")
                        .HasColumnType("bigint");

                    b.Property<string>("PodaciUplata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredhodnoObrazovanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudijskiProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrojIndeksa");

                    b.HasIndex("JMBG");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AkademskaGodina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNaPredmetu", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JMBG")
                        .HasColumnType("bigint");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JMBG");

                    b.ToTable("StudentskaSluzba", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrajanjeUGodinama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Namjena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.Property<long>("ZahtjevId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.HasIndex("ZahtjevId");

                    b.ToTable("Uvjerenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumRjesavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipZahtjeva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Zahtjev", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Zahtjev", "Zahtjev")
                        .WithMany()
                        .HasForeignKey("ZahtjevId");

                    b.Navigation("Korisnik");

                    b.Navigation("StudentskaSluzba");

                    b.Navigation("Zahtjev");
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnoOsoblje", "NastavnoOsoblje")
                        .WithMany()
                        .HasForeignKey("NastavnoOsobljeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NastavnoOsoblje");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.NastavnoOsoblje", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnoOsoblje", "NastavnoOsoblje")
                        .WithMany()
                        .HasForeignKey("NastavnoOsobljeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NastavnoOsoblje");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnoOsoblje", "NastavnoOsoblje")
                        .WithMany()
                        .HasForeignKey("NastavnoOsobljeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NastavnoOsoblje");

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.HasOne("StudentHub.Models.NastavniPlan", "NastavniPlan")
                        .WithMany()
                        .HasForeignKey("NastavniPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.NastavnoOsoblje", "NastavnoOsoblje")
                        .WithMany()
                        .HasForeignKey("NastavnoOsobljeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NastavniPlan");

                    b.Navigation("NastavnoOsoblje");
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.HasOne("StudentHub.Models.Ispit", "Ispit")
                        .WithMany()
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Zahtjev", "Zahtjev")
                        .WithMany()
                        .HasForeignKey("ZahtjevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");

                    b.Navigation("Zahtjev");
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });
#pragma warning restore 612, 618
        }
    }
}
