// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHub.Data;

#nullable disable

namespace WebApplication1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250110152758_migracijaBrojDeset")]
    partial class migracijaBrojDeset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Dokument", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<long?>("KorisnikId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Ispit", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Korisnik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnik", (string)null);

                    b.HasDiscriminator<int>("Uloga").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GodinaStudija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("NastavniPlan", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<long?>("KorisnikId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("Obavjestenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<float>("Vrijednost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocjena", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<long?>("NastavniPlanId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("NastavniPlanId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Predmet", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.PredmetAsistent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("PredmetId");

                    b.ToTable("PredmetAsistent", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.PredmetProfesor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfesorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("PredmetProfesor", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IspitId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datumPrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IspitId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prijava", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AkademskaGodina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNaPredmetu", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrajanjeUGodinama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Namjena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Uvjerenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumRjesavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusZahtjeva")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipZahtjeva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Zahtjev", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Asistent", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("AsistentTitula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("StudentHub.Models.Profesor", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("ProfesorTitula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("BrojIndeksa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<string>("PredhodnoObrazovanje")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<long?>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ZahtjevId")
                        .HasColumnType("bigint");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ZahtjevId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId");

                    b.Navigation("Asistent");

                    b.Navigation("Korisnik");

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asistent");

                    b.Navigation("Korisnik");

                    b.Navigation("Profesor");

                    b.Navigation("StudentskaSluzba");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.NastavniPlan", "NastavniPlan")
                        .WithMany()
                        .HasForeignKey("NastavniPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Asistent");

                    b.Navigation("NastavniPlan");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("StudentHub.Models.PredmetAsistent", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistent");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("StudentHub.Models.PredmetProfesor", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.HasOne("StudentHub.Models.Ispit", "Ispit")
                        .WithMany()
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Asistent", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Asistent", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.Profesor", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.StudentskaSluzba", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId");

                    b.HasOne("StudentHub.Models.Zahtjev", "Zahtjev")
                        .WithMany()
                        .HasForeignKey("ZahtjevId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Predmet");

                    b.Navigation("Zahtjev");
                });
#pragma warning restore 612, 618
        }
    }
}
