// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHub.Data;

#nullable disable

namespace StudentHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616214401_migracija10")]
    partial class migracija10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.AsistentStudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("AsistentStudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Dokument", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.DokumentSlike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DokumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DokumentId");

                    b.ToTable("DokumentSlike", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Arhivirano")
                        .HasColumnType("bit");

                    b.Property<decimal>("BrojBodova")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("NastavniPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UslovZaPolaganje")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NastavniPlanId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("Ispit", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Komentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IspitId")
                        .HasColumnType("bigint");

                    b.Property<long>("KorisnikId")
                        .HasColumnType("bigint");

                    b.Property<string>("MentionedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("NastavnaAktivnostId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrilogPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Vidljivost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IspitId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("NastavnaAktivnostId");

                    b.HasIndex("StudentId");

                    b.ToTable("Komentar", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.KomentarVidljivost", b =>
                {
                    b.Property<long>("KomentarId")
                        .HasColumnType("bigint");

                    b.Property<long>("KorisnikId")
                        .HasColumnType("bigint");

                    b.HasKey("KomentarId", "KorisnikId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KomentarVidljivosti");
                });

            modelBuilder.Entity("StudentHub.Models.Korisnik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnik", (string)null);

                    b.HasDiscriminator<int>("Uloga").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentHub.Models.NastavnaAktivnost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumVrijemeOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KodAktivanDo")
                        .HasColumnType("datetime2");

                    b.Property<string>("KodZaPrisustvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManuelnoOtkljucano")
                        .HasColumnType("bit");

                    b.Property<bool>("ManuelnoZakljucano")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VrijemeGenerisanjaKoda")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.ToTable("NastavnaAktivnost", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.NastavniMaterijal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("NastavnaAktivnostId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NastavnaAktivnostId");

                    b.ToTable("NastavniMaterijal", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.NastavniMaterijalFajl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("NastavniMaterijalId")
                        .HasColumnType("bigint");

                    b.Property<string>("PutanjaDoFajla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipFajla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NastavniMaterijalId");

                    b.ToTable("NastavniMaterijalFajl", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GodinaStudija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("NastavniPlan", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<long?>("KorisnikId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Obavjestenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.ObavjestenjeStudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ObavjestenjeId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObavjestenjeId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("ObavjestenjeStudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("NastavnaAktivnostId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<float>("Vrijednost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NastavnaAktivnostId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocjena", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<long?>("NastavniPlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PragPrisustvaPredavanja")
                        .HasColumnType("int");

                    b.Property<int?>("PragPrisustvaUkupno")
                        .HasColumnType("int");

                    b.Property<int?>("PragPrisustvaVjezbe")
                        .HasColumnType("int");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Semestar")
                        .HasColumnType("int");

                    b.Property<long?>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipPredmeta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("NastavniPlanId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("Predmet", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.PredmetAsistent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AsistentId")
                        .HasColumnType("bigint");

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsistentId");

                    b.HasIndex("PredmetId");

                    b.ToTable("PredmetAsistent", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.PredmetProfesor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfesorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("PredmetProfesor", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Bodovi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<long>("IspitId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IspitId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prijava", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.PrisustvoNaAktivnosti", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("NastavnaAktivnostId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VrijemeEvidentiranja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NastavnaAktivnostId");

                    b.HasIndex("StudentId");

                    b.ToTable("PrisustvoNaAktivnosti", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.ProfesorStudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("ProfesorStudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AkademskaGodina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AspNetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNaPredmetu", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentStudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("StudentStudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzbaStudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentskaSluzbaId");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("StudentskaSluzbaStudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrajanjeUGodinama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudijskiProgram", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgramIzborniLimit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<int>("MaxIzborniPredmeti")
                        .HasColumnType("int");

                    b.Property<int>("MinIzborniPredmeti")
                        .HasColumnType("int");

                    b.Property<long>("StudijskiProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudijskiProgramId");

                    b.ToTable("StudijskiProgramIzborniLimit", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Namjena")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentskaSluzbaId")
                        .HasColumnType("bigint");

                    b.Property<int>("VrstaUvjerenja")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("Uvjerenje", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumRjesavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusZahtjeva")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipZahtjeva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Zahtjev", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.ZahtjevZaPrisustvo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("KodUnesen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NastavnaAktivnostId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Odbijen")
                        .HasColumnType("bit");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VrijemePodnosenja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NastavnaAktivnostId");

                    b.HasIndex("StudentId");

                    b.ToTable("ZahtjevZaPrisustvo", (string)null);
                });

            modelBuilder.Entity("StudentHub.Models.Asistent", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("AsistentTitula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AsistentTitula");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("StudentHub.Models.Profesor", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("ProfesorTitula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ProfesorTitula");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.Property<string>("BrojIndeksa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<bool>("IzborIzbornihPredmetaZakljucan")
                        .HasColumnType("bit");

                    b.Property<long?>("NastavniPlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrethodnoObrazovanje")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Semestar")
                        .HasColumnType("int");

                    b.HasIndex("NastavniPlanId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.HasBaseType("StudentHub.Models.Korisnik");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.AsistentStudijskiProgram", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany("AsistentStudijskiProgrami")
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany("AsistentStudijskiProgrami")
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistent");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.DokumentSlike", b =>
                {
                    b.HasOne("StudentHub.Models.Dokument", "Dokument")
                        .WithMany("Slike")
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dokument");
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.HasOne("StudentHub.Models.NastavniPlan", "NastavniPlan")
                        .WithMany()
                        .HasForeignKey("NastavniPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NastavniPlan");

                    b.Navigation("Predmet");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Komentar", b =>
                {
                    b.HasOne("StudentHub.Models.Ispit", "Ispit")
                        .WithMany("Komentari")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "MentionedUser")
                        .WithMany()
                        .HasForeignKey("MentionedUserId");

                    b.HasOne("StudentHub.Models.NastavnaAktivnost", "NastavnaAktivnost")
                        .WithMany("Komentari")
                        .HasForeignKey("NastavnaAktivnostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ispit");

                    b.Navigation("Korisnik");

                    b.Navigation("MentionedUser");

                    b.Navigation("NastavnaAktivnost");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.KomentarVidljivost", b =>
                {
                    b.HasOne("StudentHub.Models.Komentar", "Komentar")
                        .WithMany("VidljivostKorisnici")
                        .HasForeignKey("KomentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komentar");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("StudentHub.Models.NastavnaAktivnost", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany("NastavneAktivnosti")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniMaterijal", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnaAktivnost", "NastavnaAktivnost")
                        .WithMany("NastavniMaterijali")
                        .HasForeignKey("NastavnaAktivnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NastavnaAktivnost");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniMaterijalFajl", b =>
                {
                    b.HasOne("StudentHub.Models.NastavniMaterijal", "NastavniMaterijal")
                        .WithMany("Fajlovi")
                        .HasForeignKey("NastavniMaterijalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NastavniMaterijal");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniPlan", b =>
                {
                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Asistent");

                    b.Navigation("Korisnik");

                    b.Navigation("Profesor");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.ObavjestenjeStudijskiProgram", b =>
                {
                    b.HasOne("StudentHub.Models.Obavjestenje", "Obavjestenje")
                        .WithMany("ObavjestenjeStudijskiProgrami")
                        .HasForeignKey("ObavjestenjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany("ObavjestenjeStudijskiProgrami")
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obavjestenje");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Ocjena", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnaAktivnost", "NastavnaAktivnost")
                        .WithMany("Ocjene")
                        .HasForeignKey("NastavnaAktivnostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NastavnaAktivnost");

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentHub.Models.NastavniPlan", "NastavniPlan")
                        .WithMany()
                        .HasForeignKey("NastavniPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId");

                    b.Navigation("Asistent");

                    b.Navigation("NastavniPlan");

                    b.Navigation("Profesor");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.PredmetAsistent", b =>
                {
                    b.HasOne("StudentHub.Models.Asistent", "Asistent")
                        .WithMany("Predmeti")
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany("PredmetAsistenti")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistent");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("StudentHub.Models.PredmetProfesor", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany("PredmetProfesori")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany("Predmeti")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("StudentHub.Models.Prijava", b =>
                {
                    b.HasOne("StudentHub.Models.Ispit", "Ispit")
                        .WithMany("Prijave")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.PrisustvoNaAktivnosti", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnaAktivnost", "NastavnaAktivnost")
                        .WithMany("Prisustva")
                        .HasForeignKey("NastavnaAktivnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NastavnaAktivnost");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.ProfesorStudijskiProgram", b =>
                {
                    b.HasOne("StudentHub.Models.Profesor", "Profesor")
                        .WithMany("ProfesorStudijskiProgrami")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany("ProfesorStudijskiProgrami")
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.StudentNaPredmetu", b =>
                {
                    b.HasOne("StudentHub.Models.Predmet", "Predmet")
                        .WithMany("StudentNaPredmetima")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany("StudentNaPredmetima")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.StudentStudijskiProgram", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany("StudentStudijskiProgrami")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany("StudentStudijskiProgrami")
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzbaStudijskiProgram", b =>
                {
                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany("StudentskaSluzbaStudijskiProgrami")
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany("StudentskaSluzbaStudijskiProgrami")
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentskaSluzba");

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgramIzborniLimit", b =>
                {
                    b.HasOne("StudentHub.Models.StudijskiProgram", "StudijskiProgram")
                        .WithMany()
                        .HasForeignKey("StudijskiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudijskiProgram");
                });

            modelBuilder.Entity("StudentHub.Models.Uvjerenje", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.StudentskaSluzba", "StudentskaSluzba")
                        .WithMany()
                        .HasForeignKey("StudentskaSluzbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentskaSluzba");
                });

            modelBuilder.Entity("StudentHub.Models.Zahtjev", b =>
                {
                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.ZahtjevZaPrisustvo", b =>
                {
                    b.HasOne("StudentHub.Models.NastavnaAktivnost", "NastavnaAktivnost")
                        .WithMany()
                        .HasForeignKey("NastavnaAktivnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NastavnaAktivnost");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHub.Models.Asistent", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Asistent", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.Profesor", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.NastavniPlan", "NastavniPlan")
                        .WithMany()
                        .HasForeignKey("NastavniPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NastavniPlan");
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.HasOne("StudentHub.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("StudentHub.Models.StudentskaSluzba", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHub.Models.Dokument", b =>
                {
                    b.Navigation("Slike");
                });

            modelBuilder.Entity("StudentHub.Models.Ispit", b =>
                {
                    b.Navigation("Komentari");

                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("StudentHub.Models.Komentar", b =>
                {
                    b.Navigation("VidljivostKorisnici");
                });

            modelBuilder.Entity("StudentHub.Models.NastavnaAktivnost", b =>
                {
                    b.Navigation("Komentari");

                    b.Navigation("NastavniMaterijali");

                    b.Navigation("Ocjene");

                    b.Navigation("Prisustva");
                });

            modelBuilder.Entity("StudentHub.Models.NastavniMaterijal", b =>
                {
                    b.Navigation("Fajlovi");
                });

            modelBuilder.Entity("StudentHub.Models.Obavjestenje", b =>
                {
                    b.Navigation("ObavjestenjeStudijskiProgrami");
                });

            modelBuilder.Entity("StudentHub.Models.Predmet", b =>
                {
                    b.Navigation("NastavneAktivnosti");

                    b.Navigation("PredmetAsistenti");

                    b.Navigation("PredmetProfesori");

                    b.Navigation("StudentNaPredmetima");
                });

            modelBuilder.Entity("StudentHub.Models.StudijskiProgram", b =>
                {
                    b.Navigation("AsistentStudijskiProgrami");

                    b.Navigation("ObavjestenjeStudijskiProgrami");

                    b.Navigation("ProfesorStudijskiProgrami");

                    b.Navigation("StudentStudijskiProgrami");

                    b.Navigation("StudentskaSluzbaStudijskiProgrami");
                });

            modelBuilder.Entity("StudentHub.Models.Asistent", b =>
                {
                    b.Navigation("AsistentStudijskiProgrami");

                    b.Navigation("Predmeti");
                });

            modelBuilder.Entity("StudentHub.Models.Profesor", b =>
                {
                    b.Navigation("Predmeti");

                    b.Navigation("ProfesorStudijskiProgrami");
                });

            modelBuilder.Entity("StudentHub.Models.Student", b =>
                {
                    b.Navigation("StudentNaPredmetima");

                    b.Navigation("StudentStudijskiProgrami");
                });

            modelBuilder.Entity("StudentHub.Models.StudentskaSluzba", b =>
                {
                    b.Navigation("StudentskaSluzbaStudijskiProgrami");
                });
#pragma warning restore 612, 618
        }
    }
}
